version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c6p1l3d5
      - echo Logged in to Amazon ECR successfully

  build:
    commands:
      - echo Building Docker Image for Flask Application
      - docker build -t flask-codebuild .
      - echo Image built successfully

  post_build:
    commands:
      - echo Tagging Flask Docker image
      - docker tag flask-codebuild:latest public.ecr.aws/c6p1l3d5/flask-codebuild:latest
      - docker push public.ecr.aws/c6p1l3d5/flask-codebuild:latest
      - echo Flask image pushed to ECR

